import type { Metadata } from "next";
import "./globals.css";
import SessionContext from "@/context/SessionContext";
import NextTopLoader from "nextjs-toploader";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from "@/components/ui/toaster";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionContext>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <NextTopLoader />
          <Navbar />
          <main className="min-h-[88vh] overflow-y-auto bg-slate-50">
            <div className="flex h-full w-full items-center justify-center py-10">
              {children}
            </div>
            <Toaster />
          </main>
        </body>
      </html>
    </SessionContext>
  );
}
